In [1]:
import pandas as pd
import re

In [42]:
json_file= 'usa.gov_click_data.json'
temp_df=pd.read_json(json_file, lines =True)
# temp_df.info()
temp_df

,a,c,nk,tz,gr,g,h,l,al,hh,r,u,t,hc,cy,ll
0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,US,1,America/New_York,MA,A6qOVH,wfLQtf,orofrog,"en-US,en;q=0.8",1.usa.gov,http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/...,http://www.ncbi.nlm.nih.gov/pubmed/22415991,1333307030,1333307037,Danvers,"[42.576698, -70.954903]"
1,GoogleMaps/RochesterNY,US,0,America/Denver,UT,mwszkS,mwszkS,bitly,NaN,j.mp,http://www.AwareMap.com/,http://www.monroecounty.gov/etc/911/rss.php,1331923249,1308262393,Provo,"[40.218102, -111.613297]"
2,Mozilla/4.0 (Windows NT 6.1; MSIE 8.0; Windows...,US,1,America/New_York,DC,xxr3Qb,xxr3Qb,bitly,en-US,1.usa.gov,http://t.co/03elZC4Q,http://boxer.senate.gov/en/press/releases/0316...,1333407030,1333407035,Washington,"[38.9007, -77.043098]"
3,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,BR,0,America/Sao_Paulo,27,zCaLwp,zUtuOu,alelex88,pt-br,1.usa.gov,direct,http://apod.nasa.gov/apod/ap120312.html,1333507030,1333507044,Braz,"[-23.549999, -46.616699]"
4,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,US,0,America/New_York,MA,9b6kNl,9b6kNl,bitly,"en-US,en;q=0.8",bit.ly,http://www.shrewsbury-ma.gov/selco/,http://www.shrewsbury-ma.gov/egov/gallery/1341...,1333607030,1333607039,Shrewsbury,"[42.286499, -71.714699]"
5,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,US,0,America/New_York,MA,axNK8c,axNK8c,bitly,"en-US,en;q=0.8",bit.ly,http://www.shrewsbury-ma.gov/selco/,http://www.shrewsbury-ma.gov/egov/gallery/1341...,1333707030,1333707048,Shrewsbury,"[42.286499, -71.714699]"
6,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1...,PL,0,Europe/Warsaw,77,wcndER,zkpJBR,bnjacobs,"pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4",1.usa.gov,http://plus.url.google.com/url?sa=z&n=13319232...,http://www.nasa.gov/mission_pages/nustar/main/...,1333807030,1333807040,Luban,"[51.116699, 15.2833]"
7,Mozilla/5.0 (Windows NT 6.1; rv:2.0.1) Gecko/2...,None,0,,NaN,wcndER,zkpJBR,bnjacobs,"bg,en-us;q=0.7,en;q=0.3",1.usa.gov,http://www.facebook.com/,http://www.nasa.gov/mission_pages/nustar/main/...,1334007036,13340070364,NaN,NaN
8,Opera/9.80 (Ubuntu 14.04.6; Linux zbov; U; en)...,None,0,,NaN,wcndER,zkpJBR,bnjacobs,"en-US, en",1.usa.gov,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,http://www.nasa.gov/mission_pages/nustar/main/...,1333907030,1333907042,NaN,NaN
9,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,None,0,,NaN,zCaLwp,zUtuOu,alelex88,"pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",1.usa.gov,http://t.co/o1Pd0WeV,http://apod.nasa.gov/apod/ap120312.html,1334007030,1334007040,NaN,NaN
10,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,US,1,America/Los_Angeles,WA,vNJS4H,u0uD9q,o_4us71ccioa,"en-us,en;q=0.5",1.usa.gov,direct,https://www.nysdot.gov/rexdesign/design/commun...,1334107030,1334107040,Seattle,"[47.5951, -122.332603]"
11,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4...,US,0,America/New_York,DC,wG7OIH,A0nRz4,darrellissa,"en-us,en;q=0.5",1.usa.gov,http://t.co/ND7SoPyo,http://oversight.house.gov/wp-content/uploads/...,1334207040,1334207043,Washington,"[38.937599, -77.092796]"

In [57]:
# create empty dataframe
BitlyDF=pd.DataFrame()
BitlyDF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [4]:
# extract prowser 

def extract_browser(string):
    browser_regex = r'([A-Za-z]+.[0-9]..)'
    match = re.search(browser_regex,string)
    if match:
        return match.group(1)
    else:
        return "NotFound"

BitlyDF['web_browser'] = temp_df['a'].apply(extract_browser )
# BitlyDF.info()
# BitlyDF.style

In [5]:
#extract OS
def extract_os(string):
    os_regex = r'\((Windows|Macintosh|Ubuntu)[^)]+\)'
    match = re.search(os_regex, string)
    if match:
        return match.group(1)
    else:
        return "NotFound"

BitlyDF['operating_sys'] = temp_df['a'].apply(extract_os)
# BitlyDF.info()
# BitlyDF.style

In [6]:
# extract  URL where user come from
    
def extract_url(string):
    url_regex =r'([A-Za-z]+(\.[A-Za-z]+)+)'   
    match = re.search(url_regex,string)
    if match:
        return match.group(1)
    else:
        return "NotFound"  
BitlyDF['from_url'] = temp_df['r'].apply(extract_url)    
# BitlyDF.info()
# BitlyDF.style

In [7]:
# extract URL where the user headed to 

def extract_url(string):
    url_regex =r'([A-Za-z]+(\.[A-Za-z]+)+)'   
    match = re.search(url_regex,string)
    if match:
        return match.group(1)
    else:
        return "NotFound" 
BitlyDF['to_url'] = temp_df['u'].apply(extract_url)    
# BitlyDF.info()
# BitlyDF.style

In [8]:
# extract city where request come from 

def extract_city(string):
    city_regex = r'([^"]*)'
    match = re.search(city_regex, str(string))
    if match:
        return match.group(1)
    else:
        return "NotFound"

BitlyDF['city'] = temp_df['cy'].apply(extract_city)
# BitlyDF.info()
BitlyDF.style

In [9]:
# extract the longitude 
def extract_longt(string):
    longt_regex =r'([0-9]*\.[0-9]+)'  
    
    match = re.search(longt_regex,str(string))
    if match:
        return match.group(1)
    else:
        return "NotFound" 

BitlyDF['longitude'] = temp_df['ll'].apply(extract_longt)    
# BitlyDF.info()
# BitlyDF.style

In [10]:
# extract latitude

def extract_latt(string):
    latt_regex =r',\s(-?[0-9]*\.[0-9]+)'  
    
    match = re.search(latt_regex,str(string))
    if match:
        return match.group(1)
    else:
        return "NotFound" 

BitlyDF['latitude'] = temp_df['ll'].apply(extract_latt)    
# BitlyDF.info()
# BitlyDF.style

In [11]:
# extract time zone
def extract_tmzn(string):
    time_regex =r'([^"]*)'  
    
    match = re.search(time_regex,str(string))
    if match:
        tz = match.group(1).replace("_", "")
        if tz != "":
            return tz
    else:
        return "NotFound" 

BitlyDF['time_zone'] = temp_df['tz'].apply(extract_tmzn)    
# BitlyDF.info()
BitlyDF.style

In [99]:
# extract Time when the request started
import datetime
global unix

def extract_tin(string):

    tin_regex = r'([0-9]+)'
    match = re.search(tin_regex, str(string))
    
    if match:
        timestamp = datetime.datetime.fromtimestamp(int(match.group(1))) 
        if unix:
            return int(timestamp.timestamp())
        else:
            return timestamp.strftime('%Y/%m/%d %H:%M:%S')
    
    else:
        return None

unix = False
BitlyDF['time_in'] = temp_df['t'].apply(extract_tin)  
# BitlyDF.info
BitlyDF.style

In [13]:
# extract Time when the request is ended
import datetime

def extract_tin(string):
    tin_regex =r'([0-9]+)'  
    
    match = re.search(tin_regex,str(string))
    match = datetime.datetime.fromtimestamp(int(match.group(1))).strftime('%Y/%m/%d %H:%M:%S')
    
    if match:
        return match
    else:
        return "NotFound" 

BitlyDF['time_out'] = temp_df['hc'].apply(extract_tin)    
# BitlyDF.info()
# BitlyDF.style

In [14]:
BitlyDF = BitlyDF.replace("nan", "NotFound")
BitlyDF = BitlyDF.replace("None", "NotFound")
BitlyDF

,web_browser,operating_sys,from_url,to_url,city,longitude,latitude,time_zone,time_in,time_out
0,Mozilla/5.0,Windows,www.facebook.com,www.ncbi.nlm.nih.gov,Danvers,42.576698,-70.954903,America/NewYork,2012/04/01 21:03:50,2012/04/01 21:03:57
1,NotFound,NotFound,www.AwareMap.com,www.monroecounty.gov,Provo,40.218102,-111.613297,America/Denver,2012/03/16 20:40:49,2011/06/17 00:13:13
2,Mozilla/4.0,Windows,t.co,boxer.senate.gov,Washington,38.9007,-77.043098,America/NewYork,2012/04/03 00:50:30,2012/04/03 00:50:35
3,Mozilla/5.0,Macintosh,NotFound,apod.nasa.gov,Braz,23.549999,-46.616699,America/SaoPaulo,2012/04/04 04:37:10,2012/04/04 04:37:24
4,Mozilla/5.0,Windows,www.shrewsbury,www.shrewsbury,Shrewsbury,42.286499,-71.714699,America/NewYork,2012/04/05 08:23:50,2012/04/05 08:23:59
5,Mozilla/5.0,Windows,www.shrewsbury,www.shrewsbury,Shrewsbury,42.286499,-71.714699,America/NewYork,2012/04/06 12:10:30,2012/04/06 12:10:48
6,Mozilla/5.0,Windows,plus.url.google.com,www.nasa.gov,Luban,51.116699,15.2833,Europe/Warsaw,2012/04/07 15:57:10,2012/04/07 15:57:20
7,Mozilla/5.0,Windows,www.facebook.com,www.nasa.gov,NotFound,NotFound,NotFound,None,2012/04/09 23:30:36,2392/09/24 01:06:04
8,Opera/9.8,Ubuntu,www.facebook.com,www.nasa.gov,NotFound,NotFound,NotFound,None,2012/04/08 19:43:50,2012/04/08 19:44:02
9,Mozilla/5.0,Windows,t.co,apod.nasa.gov,NotFound,NotFound,NotFound,None,2012/04/09 23:30:30,2012/04/09 23:30:40
10,Mozilla/5.0,Windows,NotFound,www.nysdot.gov,Seattle,47.5951,-122.332603,America/LosAngeles,2012/04/11 03:17:10,2012/04/11 03:17:20
11,Mozilla/5.0,Macintosh,t.co,oversight.house.gov,Washington,38.937599,-77.092796,America/NewYork,2012/04/12 07:04:00,2012/04/12 07:04:03

In [15]:
BitlyDF.to_csv('Bitly.csv')